---

- hosts: all
  tasks:

  - name: Update repository index
    apt:
      update_cache: yes

  - name: Install Apache package
    apt:
      name: apache2
      state: latest

  - name: add php support for apache2
    apt:
      name: libapache2-mod-php
      state: latest