---

- hosts: all
  tasks:

  - name: Update repository index
    apt:
      update_cache: yes

  - name: Remove Apache package
    apt:
      name: apache2
      state: absent

  - name: Remove php support for apache2
    apt:
      name: libapache2-mod-php
      state: absent