---

- hosts: all
  tasks:

  - name: Remove Apache and PHP packages
    package:
      name: 
        - apache2
        - libapache2-mod-php
      state: absent
      update_cache: yes
    when: ansible_distribution == 'Ubuntu'

  - name: Remove Apache and PHP packages
    dnf:
      name: 
        - httpd
        - php
      state: absent
      update_cache: yes
    when: ansible_distribution == 'CentOS'