- name: install mariadb-server for Ubuntu servers
  tags: mariadb, ubuntu, db
  apt:
    name:
      - mariadb-server
    state: latest
  when: ansible_distribution == "Ubuntu"

- name: install mariadb-server for CentOS servers
  tags: mariadb, centos, db
  dnf:
    name:
      - mariadb
    state: latest
  when: ansible_distribution == "CentOS"