- name: install unzip
  package:
    name: unzip
    state: latest

- name: install terraform
  unarchive:
    src: https://releases.hashicorp.com/terraform/0.12.284/terraform_0.12.28_linux_amd64.zip
    dest: /usr/local/bin/terraform
    remote_src: yes
    owner: root
    group: root
    mode: 0755